date_time_format = "%F %R"
default_flags = "g"

[[verbs]]
invocation = "edit"
shortcut = "e"
execution = "nvim +{line} {file}"
leave_broot = false

[[verbs]]
invocation = "Edit"
shortcut = "E"
execution = "nvim +{line} {file}"
leave_broot = true

[[verbs]]
invocation = "create {subpath}"
execution = "nvim {directory}/{subpath}"
leave_broot = false

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
execution = "git difftool -y {file}"
leave_broot = false

[[verbs]]
invocation = "view"
shortcut = "v"
execution = "$PAGER {file}"
leave_broot = false

[[verbs]]
key = "home"
execution = ":select_first"

[[verbs]]
key = "end"
execution = ":select_last"
